id: PCBBC677C
initial_creation_type: ocr
source_metadata:
  volumes:
    a766827414c541fca03beca9ab5714ac:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
